[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  title_separator = "//"
  [params.goatcounter]
    host = "goatcounter.com"
    src = "https://gc.zgo.at/count.v3.js"
    integrity = "sha384-QGgNMMRFTi8ul5kHJ+vXysPe8gySvSA/Y3rpXZiRLzKPIw8CWY+a3ObKmQsyDr+a"

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["rss.xml"]
  [mediaTypes."application/atom+xml"]
    suffixes = ["atom.xml"]
  [mediaTypes."application/feed+json"]
    suffixes = ["feed.json"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    noUgly = true
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    noUgly = true
  [outputFormats.FEED]
    mediaType = "application/feed+json"
    isPlainText = true
