[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  title_separator = "//"
  [params.goatcounter]
    host = "goatcounter.com"
    src = "https://gc.zgo.at/count.v3.js"
    integrity = "sha384-QGgNMMRFTi8ul5kHJ+vXysPe8gySvSA/Y3rpXZiRLzKPIw8CWY+a3ObKmQsyDr+a"
