baseURL = "https://artero.dev"
copyright = "Copyright %d William Artero. Some rights reserved."
defaultContentLanguage = "en"
disableLiveReload = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
mainSections = ["posts"]
pygmentsCodeFences = true
pygmentsUseClasses = false
removePathAccents = true
summaryLength = 100
theme = "yocto"
title = "William Artero"

[frontmatter]
date = [":default", ":fileModTime"]
lastmod = ["lastmod","modified",":git",":fileModTime",":default"]

[imaging.exif]
disableDate = true
disableLatLong = true
includeFields = "Artist|Copyright|DocumentName|ImageUniqueID|ImageDescription|UserComment"

[languages.en]
hasCJKLanguage = false
languageCode = "en"
languageName = "English"
weight = 1

[markup.goldmark.extensions]
_merge = "deep"
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[markup.highlight]
codeFences = true
lineNos = false
noClasses = false
style = "monokai"
tabWidth = 2

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[mediaTypes."application/vnd.cloudflare.text+plain"]
delimiter = ""
suffixes = [""]

[[module.mounts]]
source = "content"
target = "content"
excludeFiles = [
  "**/*.iuml",
  "**/*.jpg.json",
  "**/*.png.json",
  "**/*.puml",
  "**/*.tmpl",
]

[[module.mounts]]
source = "static"
target = "static"
excludeFiles = [
  "**/*.mk",
  "**/Makefile",
]

[outputFormats.cloudflare-headers]
baseName = "_headers"
isPlainText = true
mediaType = "application/vnd.cloudflare.text+plain"
notAlternative = true

[outputFormats.cloudflare-redirects]
baseName = "_redirects"
isPlainText = true
mediaType = "application/vnd.cloudflare.text+plain"
notAlternative = true

[outputs]
home = [
  "cloudflare-headers",
  "cloudflare-redirects",
  "feed",
  "html",
  "rss",
  "webappmanifest",
]
page = ["html"]
section = ["html"]
taxonomy = ["html"]
term = ["feed", "html", "rss"]

[pagination]
disableAliases = true
pagerSize = 10

[permalinks]
posts = "posts/:contentbasename"
redirects = "/:contentbasename"

[privacy]
dispus.disable = true
googleAnalytics.disable = true
youtube.privacyEnhanced = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
category = "categories"
tag = "tags"
