highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
  hl_Lines: ""
  lineAnchors: ""
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: true
  noClasses: false
  style: monokai
  tabWidth: 2

goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute:
      block: false
      title: false
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    unsafe: true
    hardWraps: false
    xhtml: false

tableOfContents:
  startLevel: 2
  endLevel: 6
