# yaml-language-server: $schema=../../.meta/schemas/hugo.schema.json#/properties/markup
highlight:
  codeFences: true
  lineNos: false
  noClasses: false
  style: monokai
  tabWidth: 2
goldmark:
  extensions:
    _merge: deep
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute:
      block: true
      title: true
    autoHeadingID: true
    autoHeadingIDType: github
    wrapStandAloneImageWithinParagraph: false
  renderer:
    unsafe: false
    hardWraps: false
    xhtml: false
tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 2
