# yaml-language-server: $schema=../../.meta/schemas/hugo.schema.json#/properties/menu
main:
- name: About
  pageRef: about
  weight: 1
- name: Chat
  url: https://cal.com/artero
  weight: 2
  params:
    rel: noreferrer noopener nofollow external
    target: _blank
- name: LinkedIn
  url: https://linkedin.com/in/wwmoraes
  weight: 10
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
- name: GitHub
  url: https://github.com/wwmoraes
  weight: 20
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
- name: Research
  url: https://www.zotero.org/wwmoraes/library
  weight: 30
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
- name: Bookshelf
  url: https://www.goodreads.com/wwmoraes
  weight: 40
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
footer:
- name: Posts
  pageRef: posts
  weight: 1
- name: Categories
  pageRef: categories
  weight: 2
- name: Tags
  pageRef: tags
  weight: 3
social:
- name: Telegram
  url: https://t.me/wwmoraes
  weight: 11
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
- name: Hachyderm
  url: https://hachyderm.io/@wwmoraes
  weight: 12
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
- name: Mastodon
  url: https://mastodon.social/@wwmoraes
  weight: 13
  params:
    rel: noreferrer noopener nofollow external me
    target: _blank
# - name: X
#   url: https://x.com/wwmoraes
# - name: CodePen
#   url: https://codepen.io/wwmoraes
# - name: CodeSandbox
#   url: https://codesandbox.io/u/wwmoraes
