version = 1

[approve]
auto_approve_usernames = ["github-actions", "pre-commit-ci", "wwmoraes"]

[merge]
automerge_label = "automerge"
require_automerge_label = true
method = "rebase_fast_forward"
delete_branch_on_merge = true

[update]
always = false
require_automerge_label = true
