# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  labels:
  - automerge
  schedule:
    interval: weekly
- package-ecosystem: gomod
  directory: /
  labels:
  - automerge
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: /
  labels:
  - automerge
  schedule:
    interval: weekly
