# yaml-language-server: $schema=../../.meta/schemas/hugo.schema.json#/properties/params
article:
  showEdit: true
  editURL: https://github.com/wwmoraes/site/blob/staging/
  editAppendPath: true

goatcounter:
  code: ""

giscus: null
