version: "2"

exclude_patterns:
- .frontmatter/*
- .github/*
- .make/*
- .vscode/*
- "content/**/*.go"
- .env*
- "**/*.jpg"
- "**/*.png"
- "**/*.json"
- "**/*.afphoto"
- "**/*.afdesign"

plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
    config:
      strings:
      - FIX
      - TODO
      - BUG
      - "[ ]"
  git-legal:
    enabled: true
  gofmt:
    enabled: true
  golangci:
    enabled: true
  govet:
    enabled: true
  hadolint:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  semgrep:
    enabled: true
  stylelint:
    enabled: true
  sass-lint:
    enabled: true
