# yaml-language-server: $schema=https://raw.githubusercontent.com/golangci/golangci-lint/refs/tags/v2.10.1/jsonschema/golangci.jsonschema.json
version: "2"
run:
  go: "1.22"
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  formats:
    text:
      path: stdout
    sarif:
      path: golangci-lint.sarif
linters:
  default: all
  disable:
  - asasalint
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck
  - depguard
  - durationcheck
  - embeddedstructfieldcheck # new on ~2.10 but broken, doesn't detect properly
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exhaustruct
  - exptostd
  - fatcontext
  - forbidigo
  - forcetypeassert
  - ginkgolinter
  - gochecknoglobals
  - gochecksumtype
  - gocritic
  - godot
  - godox
  - gomoddirectives
  - gosec
  - gosmopolitan
  - govet
  - iface
  - importas
  - intrange
  - ireturn
  - loggercheck
  - makezero
  - mirror
  - musttag
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nonamedreturns
  - paralleltest
  - perfsprint
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - tagliatelle
  - testifylint
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - usetesting
  - varnamelen
  - wastedassign
  - wrapcheck
  - wsl
  - zerologlint
  settings:
    embeddedstructfieldcheck:
      empty-line: true
      forbid-mutex: true
    exhaustruct:
      exclude:
      - .+/cobra\.Command$
      - .+/hugo\.Config$
      - github\.com/wwmoraes/site/pkg/schema\..+
      - github\.com/wwmoraes/site/pkg/functional\.Result$
    mnd:
      ignored-numbers:
      - "0o640"
      - "100" # used to calculate percents
      ignored-functions:
      - \.Int$
      - \.IntP$
      - \.MkdirAll$
      - \.OpenFile$
      - \.WriteFile$
      - make
      - os.Exit
      - strings.SplitN
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    # exclude OpenLibrary JSON tags as we need them to match the upstream
    - linters:
      - tagliatelle
      path: pkg/openlibrary/.*
      text: 'json\(camel\):'
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
