# cspell:disable
issues:
  exclude-rules:
  # exclude OpenLibrary JSON tags as we need them to match the upstream
  - linters:
    - tagliatelle
    text: 'json\(camel\):'
    path: 'pkg/openlibrary/.*'
linters:
  enable-all: true
  fast: true # TODO disable fast linters only
  disable:
  - depguard # too much nitpicking and gatekeeping
  - godox # no need; there's a VSCode extension + Sonar reports
  # - gofumpt # false-positive on a comment!
  - gomoddirectives # broken, reports a replace directive that doesn't exist
  ## deprecated
  - execinquery
  - gomnd
linters-settings:
  exhaustruct:
    exclude:
    - .+/cobra\.Command$
    - .+/hugo\.Config$
    - github\.com/wwmoraes/site/pkg/schema\..+
    - github\.com/wwmoraes/site/pkg/functional\.Result$
  mnd:
    ignored-functions:
    - '\.Int$'
    - '\.IntP$'
    - '\.MkdirAll$'
    - '\.OpenFile$'
    - '\.WriteFile$'
    - make
    - strings.SplitN
    ignored-numbers:
    - '0o640'
output:
  show-stats: true
  sort-results: true
  formats:
  - format: colored-line-number
run:
  allow-parallel-runners: true
  allow-serial-runners: true
  modules-download-mode: readonly
  go: "1.22"
