# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json
pre-commit:
  commands:
    typos:
      run: >-
        {cmd}
        | reviewdog -name typos -filter-mode=nofilter -reporter=github-check -fail-on-error -f=typos
    editorconfig-checker:
      run: >-
        {cmd}
        | reviewdog -name editorconfig-checker -filter-mode=nofilter -reporter=github-check -fail-on-error -efm="%f:%l:%c: %m"
      env:
        ARGS: -f gcc
    vale:
      run: >-
        {cmd}
        | reviewdog -name vale -filter-mode=nofilter -reporter=github-check -efm="%f:%l:%c:%m"
      env:
        ARGS: --output=line
    stylelint:
      run: >-
        {cmd}
        | reviewdog -name stylelint -filter-mode=nofilter -reporter=github-check -fail-on-error -f=stylelint
      env:
        ARGS: --config-basedir $HOME/.config/yarn/global/node_modules
    golangci-lint:
      run: >-
        {cmd}
        | reviewdog -name golangci-lint -filter-mode=nofilter -reporter=github-check -fail-on-error -f=golangci-lint
