linters:
  UrlFormat: # garbage, we use CDNs
    enabled: false

  IdSelector: # why tho
    enabled: false

  SelectorDepth: # beggars can't be choosers
    enabled: false

  ImportPath: # ditto
    enabled: false

  StringQuotes:
    style: double_quotes

  PropertySpelling:
    extra_properties:
    - gap

  VendorPrefix:
    enabled: false # TODO add bourbon, re-enable and fix code <https://github.com/thoughtbot/bourbon>
