extends: stylelint-config-standard-scss
ignoreFiles:
- "tmp/**"
- "**/*.css"
- "themes/pico/assets/css/pico/**/*"
rules:
  alpha-value-notation: number
  color-function-notation: modern
  selector-no-vendor-prefix:
  - true
  - ignoreSelectors:
    - "/-moz-.*/"
    - "/-ms-.*/"
    - "/-webkit-.*/"
  property-no-vendor-prefix:
  - true
  - ignoreSelectors:
    - "/-moz-.*/"
  "scss/no-global-function-names": false
  value-keyword-case:
  - lower
  - ignoreKeywords:
    - currentColor
    ignoreProperties:
    - /font-family/
  media-feature-range-notation: prefix
  rule-empty-line-before:
  - always
  - except:
    - after-single-line-comment
    ignore:
    - first-nested
