StylesPath = .styles
# MinAlertLevel = error

Packages = Hugo, proselint, Readability, Joblint, write-good, alex
Vocab = Blog, Companies, Names

SkippedScopes = script, style, pre, figure, blockquote

[*.md]
BasedOnStyles = Vale, proselint, Readability, Joblint, write-good, alex

Joblint.Competitive = OFF
Joblint.Gendered = OFF
Joblint.Visionary = warning
Readability.AutomatedReadability = suggestion
Readability.ColemanLiau = suggestion
Readability.FleschKincaid = suggestion
Readability.FleschReadingEase = suggestion
Readability.GunningFog = suggestion
Readability.LIX = suggestion
Readability.SMOG = suggestion
Vale.Spelling = error
alex.Condescending = warning
alex.Gendered = OFF
alex.ProfanityMaybe = OFF
alex.ProfanityUnlikely = OFF
proselint.Annotations = OFF
write-good.E-Prime = OFF
write-good.Passive = warning

[content/*.md]
BlockIgnores = (?sm)({{< \w+ [^>]* ?>}}.*?{{< ?/ ?\w+ >}})
