#:schema https://raw.githubusercontent.com/cocogitto/cocogitto/refs/heads/main/website/public/cog-schema.json

branch_whitelist = ["master"]
from_latest_tag = true
post_bump_hooks = [
  "git push",
  "git push {{version}}",
  "goreleaser release --clean --release-notes CHANGELOG.md",
]
pre_bump_hooks = ["goreleaser check", "goreleaser healthcheck", "remake check"]

[git_hooks.commit-msg]
script = """#!/usr/bin/env sh
grep -q "^fixup! " "$1" || cog verify --file "$1"
git interpret-trailers --in-place --trailer signer --trailer patch-stack --trim-empty "$1"
"""

[git_hooks.post-checkout]
script = "remake checkout"

[git_hooks.pre-commit]
script = """#!/usr/bin/env sh
STASHED=$(git stash push --keep-index --include-untracked | grep -vqFx "No local changes to save"; echo $?)
remake check
status=$?
test $STASHED -eq 0 && git stash pop --quiet || true
exit $status
"""

[git_hooks.pre-push]
script = """#!/usr/bin/env sh
STASHED=$(git stash push --keep-index --include-untracked | grep -vqFx "No local changes to save"; echo $?)
remake all test git-check
status=$?
test $STASHED -eq 0 && git stash pop --quiet || true
exit $status
"""

[changelog]
authors = [{ signature = "William Artero", username = "wwmoraes" }]
owner = "wwmoraes"
package_template = "package_remote"
path = "CHANGELOG.md"
remote = "github.com"
repository = "gotell"
template = "remote"
