define HUGO_SOURCES
$(strip
$(shell git ls-files {assets,config,content,data,i18n,layouts,static,themes}'/**/*.*')
$(patsubst %.json,%,$(strip $(shell git ls-files {archetypes,assets,content}'/**/*.'{jpg,png}'.json')))
$(patsubst %.d2,%.svg,$(strip $(shell git ls-files 'content/**/*.d2')))
$(patsubst %/params.toml,%/server.toml,$(wildcard config/*/headers/params.toml))
$(patsubst %/params.toml,%/server.toml,$(wildcard config/*/redirects/params.toml))
static
)
endef

.PHONY: content
#: Updates generated content files.
content: $(filter content/%,${HUGO_SOURCES})

.PHONY: config
#: Updates generated config files.
config: $(filter config/%,${HUGO_SOURCES})

#: Generates all environments' site assets.
dist: dist/development dist/staging dist/production

#: Generates development site assets.
dist/development:

#: Generates staging site assets.
dist/staging:

#: Generates production site assets.
dist/production:

.PHONY: static
#: Updates static assets.
static:
	@${MAKE} -C $@

################################################################################
# Make magic, not war :)
################################################################################

config/%/headers/server.toml: config/%/headers/params.toml
	$(info (re)-generating $@...)
	$(file >$@,# Settings generated by Makefile. DO NOT EDIT.)
	@remarshal --to json $< - \
	| jq '.server.headers | map({for: .for, values: (.values | map_values(if . | type == "string" then . else if . | type == "object" then (.separator as $$separator | .values | join($$separator)) else "" end end))})' \
	| remarshal --from json --to toml --wrap headers - - >> $@

config/%/redirects/server.toml: config/%/redirects/params.toml
	$(info (re)-generating $@...)
	$(file >$@,# Settings generated by Makefile. DO NOT EDIT.)
	@remarshal --to json $< - \
	| jq '.server.redirects | map(if has("force") | not then .force |= true end)' \
	| remarshal --from json --to toml --wrap redirects - - >> $@

content/%.svg: content/%.d2 vars.d2
	$(info generating $@...)
	@cat vars.d2 $< | d2 - $@

dist/%: ${HUGO_SOURCES}
	$(info generating static site for environment '$*' at '$@'...)
	@hugo --gc --cleanDestinationDir --environment '$*' --destination '$@'
