@startuml table-meta-index
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/hacker/puml-theme-hacker.puml
!theme hacker
skinparam BackgroundColor #1f202b
skinparam SwimlaneTitleFontColor #000000
|c| code
split
-[hidden]->
start
:waldo.key<
split again
|t| table
-[hidden]->
(A)
end split
if (is key set?) then (yes)
  :value/
else (no)
  if (is metatable set?) then (no)
    :nil/
  else (yes)
    |m| metatable
    if (is __index set?) then (no)
      :nil/
    else (yes)
      if (type(__index)) then (table)
      (A)
      else (function)
        :__index(tbl,key)/
      endif
    endif
  endif
endif
|t|
:return>
|c|
stop
@enduml
