@startuml table-index
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/hacker/puml-theme-hacker.puml
!theme hacker
skinparam BackgroundColor #1f202b
skinparam SwimlaneTitleFontColor #000000
|c| code
start
:waldo.key<
|t| table
if (is key set?) then (yes)
  :value/
else (no)
  if (is metatable set?) then (no)
    :nil/
  else (yes)
    :magic|
  endif
endif
:return>
|c|
stop
@enduml
