graph TD;
  waldoGetKey>waldo.key]
  subgraph metatable
    metaHasIndex{{is __index set?}}
    metaIndexType{{"type(__index)"}}
    metaNil[/nil/]
    metaCallIndex(["__index(tbl,key)"])
    metaIndexGetKeyValue(["__index[key]"])
  end
  subgraph table
    tableHasKey{{"is key set?"}}
    tableHasMetatable{{is metatable set?}}
    tableValue[/value/]
    tableNil[/nil/]
  end
  output([return])

  %% table entry point
  waldoGetKey --> tableHasKey

  %% table happy flow
  tableHasKey -- yes --> tableValue
  tableValue --> output

  %% not-so-happy flow
  tableHasKey -- no --> tableHasMetatable
  tableHasMetatable -- no --> tableNil
  tableNil --> output

  %% metatable entrypoint
  tableHasMetatable -- yes --> metaHasIndex
  metaHasIndex -- yes --> metaIndexType

  %% table index metamethod
  metaIndexType -- table --> metaIndexGetKeyValue
  metaIndexGetKeyValue -- get --> tableHasKey

  %% function index metamethod
  metaIndexType -- function --> metaCallIndex
  metaCallIndex --> output

  %% no index metamethod
  metaHasIndex -- no --> metaNil
  metaNil --> output
