config/%/headers/server.toml: config/%/headers/params.toml
	$(info (re)-generating $@...)
	$(file >$@,# Settings generated by Makefile. DO NOT EDIT.)
	@remarshal --to json $< - \
	| jq '.server.headers | map({for: .for, values: (.values | map_values(if . | type == "string" then . else if . | type == "object" then (.separator as $$separator | .values | join($$separator)) else "" end end))})' \
	| remarshal --from json --to toml --wrap headers - - >> $@

config/%/redirects/server.toml: config/%/redirects/params.toml
	$(info (re)-generating $@...)
	$(file >$@,# Settings generated by Makefile. DO NOT EDIT.)
	@remarshal --to json $< - \
	| jq '.server.redirects | map(if has("force") | not then .force |= true end)' \
	| remarshal --from json --to toml --wrap redirects - - >> $@
