name: Build
on:
  push:
    paths:
    - .github/workflows/build.yaml
    - .make/*.mk
    - cmd/*
    - go.mod
    - go.sum
    - internal/*
    - pkg/*
    - shell.nix
    - Makefile
  pull_request:
    types:
    - synchronize
    - reopened
    - opened
    paths:
    - .github/workflows/build.yaml
    - .make/*.mk
    - Makefile
    - cmd/*
    - flake.lock
    - flake.nix
    - go.mod
    - go.sum
    - internal/*
    - pkg/*
    - shell.nix
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup nix
      uses: ./.github/actions/nix
    - name: cache go
      uses: wwmoraes/actions/golang/cache@master
    - name: download modules
      run: go mod download -x
    - name: build
      run: remake bin/site
    - name: attest binary
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: bin/site
    - name: deliver
      uses: actions/upload-artifact@v4
      with:
        name: site-binary
        path: bin/site
