name: Deployment

on:
  workflow_run:
    branches: ['*']
    workflows: [Integration]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:

    - name: Await CF Pages
      uses: WalshyDev/cf-pages-await@v1
      timeout-minutes: 5
      with:
        apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
        accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        project: ${{ vars.CLOUDFLARE_PROJECT }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        commitHash: ${{ github.sha }}

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
