name: Deployment
on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup nix
      uses: ./.github/actions/nix
    - name: deploy to CF Pages
      run: |-
        remake deploy
        remake purge-cache
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT }}
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        GIT_BRANCH: ${{ github.ref_name }}
        GIT_COMMIT_HASH: ${{ github.sha }}
