name: Deployment
on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
env:
  DEVSHELL: default
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup nix
      uses: ./.github/actions/nix
    - name: deploy to CF Pages
      run: |-
        set -eu
        yes | just deploy
        just purge-cache
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        GIT_BRANCH: ${{ github.ref_name }}
        GIT_COMMIT_HASH: ${{ github.sha }}
