name: Integration
on:
  push:
    paths-ignore:
    - .meta/*
  pull_request:
    types:
    - synchronize
    - reopened
    - opened
    paths-ignore:
    - .meta/*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-tags: true
        persist-credentials: false
    - name: setup nix
      uses: ./.github/actions/nix
    - name: check
      run: remake check
    - name: assert clean repository
      run: test -z "$(git diff --shortstat | head -c1)"
    - name: upload golangci-lint SARIF
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ hashFiles('golangci-lint.sarif') != '' }}
      with:
        sarif_file: golangci-lint.sarif
        category: golangci-lint
        token: ${{ secrets.GITHUB_TOKEN }}
